### PR TITLE
Improve HTML Processing Towards XML->Map Specification And Add Tests

### PR DESCRIPTION
**Pull request by JFryy**
## Description
Tried this with a variety of sites for verifying correctness, will merge once unit tests complete and if anyone would like to give a review if nothing else (if you're not too opinionated on the implementation but rather the end result just to validate correctness).

 I've done some tests with fq and qq comparison, the only difference is some trimming of space trailing newlines and things of that nature and doesn't look harmful or massively inconvenient.

 ```shell
 ❯ export site=example.com  && curl $site | go run . -i html > qq_o.json && curl $site | fq > fq_o.json && diff qq_o.json fq_o.json

 ```

## Changes

- [x] **🛠️ Code Changes**
  - [x] Implemented feature 
  - [ ] Fixed bug
  - [ ] Refactored component 
  - [ ] Updated documentation

- [x] **🐛 Testing**
  - [x] Added unit tests for new functionality
  - [x] Updated existing tests to reflect changes
  - [x] Ran all tests locally

- [ ] **📄 Documentation**
  - [ ] Updated README or documentation files as needed

### CODE REVIEW

**Comment by JFryy** [comment]
Tests here need a lot of work but should cover the most critical parts of this better. HTML parsing is improved, but I should probably bundle in some changes for CSV possibly in this batch so values are returned as list of maps sooner rather than later to not effect existing users (too much) since that besides some edge-cases where I am not sure at all (like ini rendering map strings since it can only handle scalar values) besides adding new codecs the best place for improvements besides removing dependencies on external libraries where its not totally needed or "bloated" for lack of better words.

**Comment by wader** [comment]
Feel free to use or copy the xml/html tests from fq https://github.com/wader/fq/tree/master/format/xml/testdata

**Comment by JFryy** [comment]
Thank you for sharing! Definitely like using assertions with stdout (if i grokked that right on a eyeballing it quickly) it seems comprehensive but simple, I think I'll use a similar method and just copy your tests to ensure xml/html is covered thoroughly seeing as it bit more problematic. Will include some additions (csv list of maps, newline ".txt" file parsing as an option) bundled in this change along with that relatively soon.

**Comment by wader** [comment]
Yeap more or less but there is an interface https://github.com/wader/fq/blob/master/pkg/interp/interp.go#L145-L158 which the test framework (and normal CLI) implements which allow to run tests faster, no new process per test etc, and also do some other tricks

**Pull request merged**
